project_id = "eeqhrgdyhuisbamudfxc"

[functions.rollover-tasks]
verify_jwt = false

[functions.generate-recurring-tasks]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.fetch-og]
verify_jwt = false

[functions.auto-service-tag]
verify_jwt = false
